More changes for nginx rev proxy

diff --git a/vagrant/Vagrantfile b/vagrant/Vagrantfile
--- a/vagrant/Vagrantfile
+++ b/vagrant/Vagrantfile
@@ -8,6 +8,10 @@
 # Useful for testing and for base for building production images.
 #USE
 #	cd vagrant; vagrant up
+#	For VM guests on Ubuntu Xenial
+#	Requires Virtual box host only nework vboxnet0 setup with virtual box dhcp server
+#	running on host. And you may need to run:
+#	$ VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0
 #AUTHOR
 # (C) 2016 Gary Wallis unxs@unxs.io for Adhoc Engineering S.A.
 
@@ -16,13 +20,13 @@ Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/xenial64"
 
   config.vm.provider :virtualbox do |vb|
-    vb.name = "adhoc0"
+	vb.name = "adhoc0"
+	config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet0', :adapter => 2
   end
 
-  config.vm.network "public_network", ip: "10.0.0.17"
+  config.vm.provision "shell", inline: <<-SHELL
 
-    config.vm.provision "shell", inline: <<-SHELL
-        grep -q 'mesg n' /root/.profile && sed -i '/mesg n/d' /root/.profile && echo 'Ignore the previous error...';
+	grep -q 'mesg n' /root/.profile && sed -i '/mesg n/d' /root/.profile && echo 'Ignore the previous error...';
 	apt-get update --assume-yes;
 	if [ "$?" != "0" ];then
           echo "apt-get update failed";
@@ -64,12 +68,31 @@ Vagrant.configure("2") do |config|
           echo "docker systemd start failed";
           exit 1;
 	fi
+
+	#this creates the dockernginxadhox_backend network
+	#it must be created once and before any other containers.
+	#automated reverse proxy nginx-proxy
+	cd docker-odoo-adhoc;
+	cd docker-nginx-adhoc;
+	docker-compose up -d;
+	if [ "$?" != "0" ];then
+          echo "docker-compose up nginx failed";
+          exit 1;
+	fi
+
+	#start db and odoo
+        cd ~;
 	cd docker-odoo-adhoc;
 	docker-compose up -d;
 	if [ "$?" != "0" ];then
-          echo "docker-compose up failed";
+          echo "docker-compose up odoo failed";
           exit 1;
 	fi
-	echo "odoo available on port 8069";
-    SHELL
+
+	#make docker containers persist reboot
+	docker update --restart=always dockerodooadhoc_odoo_1;
+	docker update --restart=always dockerodooadhoc_db_1;
+	docker update --restart=always nginx-proxy;
+	echo "odoo available on port 8069 local and via nginx on port 80";
+  SHELL
 end
